apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: kibana-ns
  # labels:
  #   run: kibana
spec:
  type: LoadBalancer
  selector:
    # component: kibana
    app: kibana
  ports:
    - name: http
      port: 5601
      protocol: TCP
