apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging-service
  namespace: elastic-ns
spec:
  type: NodePort
  selector:
    component: elasticsearch
  ports:
    - name: http
      port: 9200
      nodePort: 31000
      protocol: TCP
